pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            url = 'https://maven.minecraftforge.net/'
            content {
                includeGroup "net.minecraftforge.gradle"
                includeGroup "net.minecraftforge"
            }
        }
        maven {
            url = 'https://maven.parchmentmc.org'
        }
    }
}


rootProject.name = 'Theurgy KubeJS ' + minecraft_version